version: '3.7'
services:
  server:
    build: .
    ports:
      - "3001:3001"
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - server